version: '3'

services:
  db:
    # Keep same as AWS Aurora Postgres
    image: postgres:9.6.3
  migrator:
    build: .
    command: python3 manage.py migrate
    volumes:
      - .:/code
    ports:
      - "8801:8000"
    depends_on:
      - db
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8800:8000"
    depends_on:
      - migrator
